// Code generated by protoc-gen-go. DO NOT EDIT.
// source: attack.proto

package msg

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AttackBroadCast struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	RoomId               int32    `protobuf:"varint,2,opt,name=RoomId,proto3" json:"RoomId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AttackBroadCast) Reset()         { *m = AttackBroadCast{} }
func (m *AttackBroadCast) String() string { return proto.CompactTextString(m) }
func (*AttackBroadCast) ProtoMessage()    {}
func (*AttackBroadCast) Descriptor() ([]byte, []int) {
	return fileDescriptor_1cb42fc8623246e2, []int{0}
}

func (m *AttackBroadCast) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AttackBroadCast.Unmarshal(m, b)
}
func (m *AttackBroadCast) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AttackBroadCast.Marshal(b, m, deterministic)
}
func (m *AttackBroadCast) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AttackBroadCast.Merge(m, src)
}
func (m *AttackBroadCast) XXX_Size() int {
	return xxx_messageInfo_AttackBroadCast.Size(m)
}
func (m *AttackBroadCast) XXX_DiscardUnknown() {
	xxx_messageInfo_AttackBroadCast.DiscardUnknown(m)
}

var xxx_messageInfo_AttackBroadCast proto.InternalMessageInfo

func (m *AttackBroadCast) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AttackBroadCast) GetRoomId() int32 {
	if m != nil {
		return m.RoomId
	}
	return 0
}

func init() {
	proto.RegisterType((*AttackBroadCast)(nil), "msg.AttackBroadCast")
}

func init() { proto.RegisterFile("attack.proto", fileDescriptor_1cb42fc8623246e2) }

var fileDescriptor_1cb42fc8623246e2 = []byte{
	// 100 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x49, 0x2c, 0x29, 0x49,
	0x4c, 0xce, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xce, 0x2d, 0x4e, 0x57, 0xb2, 0xe5,
	0xe2, 0x77, 0x04, 0x0b, 0x3a, 0x15, 0xe5, 0x27, 0xa6, 0x38, 0x27, 0x16, 0x97, 0x08, 0x09, 0x71,
	0xb1, 0xf8, 0x25, 0xe6, 0xa6, 0x4a, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0x81, 0xd9, 0x42, 0x62,
	0x5c, 0x6c, 0x41, 0xf9, 0xf9, 0xb9, 0x9e, 0x29, 0x12, 0x4c, 0x0a, 0x8c, 0x1a, 0xac, 0x41, 0x50,
	0x5e, 0x12, 0x1b, 0xd8, 0x28, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x17, 0xac, 0x87, 0xdd,
	0x5a, 0x00, 0x00, 0x00,
}
