// Code generated by protoc-gen-go. DO NOT EDIT.
// source: login.proto

package msg

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Player struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	RoomId               int32    `protobuf:"varint,2,opt,name=RoomId,proto3" json:"RoomId,omitempty"`
	X                    float32  `protobuf:"fixed32,3,opt,name=X,proto3" json:"X,omitempty"`
	Y                    float32  `protobuf:"fixed32,4,opt,name=Y,proto3" json:"Y,omitempty"`
	Direction            int32    `protobuf:"varint,5,opt,name=Direction,proto3" json:"Direction,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Player) Reset()         { *m = Player{} }
func (m *Player) String() string { return proto.CompactTextString(m) }
func (*Player) ProtoMessage()    {}
func (*Player) Descriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{0}
}

func (m *Player) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Player.Unmarshal(m, b)
}
func (m *Player) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Player.Marshal(b, m, deterministic)
}
func (m *Player) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Player.Merge(m, src)
}
func (m *Player) XXX_Size() int {
	return xxx_messageInfo_Player.Size(m)
}
func (m *Player) XXX_DiscardUnknown() {
	xxx_messageInfo_Player.DiscardUnknown(m)
}

var xxx_messageInfo_Player proto.InternalMessageInfo

func (m *Player) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Player) GetRoomId() int32 {
	if m != nil {
		return m.RoomId
	}
	return 0
}

func (m *Player) GetX() float32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *Player) GetY() float32 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *Player) GetDirection() int32 {
	if m != nil {
		return m.Direction
	}
	return 0
}

type LoginRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{1}
}

func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

type MatchCompleteBroadCast struct {
	MatchState           int32    `protobuf:"varint,1,opt,name=MatchState,proto3" json:"MatchState,omitempty"`
	Seed                 int32    `protobuf:"varint,2,opt,name=Seed,proto3" json:"Seed,omitempty"`
	RoomId               int32    `protobuf:"varint,3,opt,name=RoomId,proto3" json:"RoomId,omitempty"`
	CurrentPlayerName    string   `protobuf:"bytes,4,opt,name=CurrentPlayerName,proto3" json:"CurrentPlayerName,omitempty"`
	Player1              *Player  `protobuf:"bytes,5,opt,name=Player1,proto3" json:"Player1,omitempty"`
	Player2              *Player  `protobuf:"bytes,6,opt,name=Player2,proto3" json:"Player2,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MatchCompleteBroadCast) Reset()         { *m = MatchCompleteBroadCast{} }
func (m *MatchCompleteBroadCast) String() string { return proto.CompactTextString(m) }
func (*MatchCompleteBroadCast) ProtoMessage()    {}
func (*MatchCompleteBroadCast) Descriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{2}
}

func (m *MatchCompleteBroadCast) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MatchCompleteBroadCast.Unmarshal(m, b)
}
func (m *MatchCompleteBroadCast) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MatchCompleteBroadCast.Marshal(b, m, deterministic)
}
func (m *MatchCompleteBroadCast) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MatchCompleteBroadCast.Merge(m, src)
}
func (m *MatchCompleteBroadCast) XXX_Size() int {
	return xxx_messageInfo_MatchCompleteBroadCast.Size(m)
}
func (m *MatchCompleteBroadCast) XXX_DiscardUnknown() {
	xxx_messageInfo_MatchCompleteBroadCast.DiscardUnknown(m)
}

var xxx_messageInfo_MatchCompleteBroadCast proto.InternalMessageInfo

func (m *MatchCompleteBroadCast) GetMatchState() int32 {
	if m != nil {
		return m.MatchState
	}
	return 0
}

func (m *MatchCompleteBroadCast) GetSeed() int32 {
	if m != nil {
		return m.Seed
	}
	return 0
}

func (m *MatchCompleteBroadCast) GetRoomId() int32 {
	if m != nil {
		return m.RoomId
	}
	return 0
}

func (m *MatchCompleteBroadCast) GetCurrentPlayerName() string {
	if m != nil {
		return m.CurrentPlayerName
	}
	return ""
}

func (m *MatchCompleteBroadCast) GetPlayer1() *Player {
	if m != nil {
		return m.Player1
	}
	return nil
}

func (m *MatchCompleteBroadCast) GetPlayer2() *Player {
	if m != nil {
		return m.Player2
	}
	return nil
}

type HeartbeatRequest struct {
	RoomId               int32    `protobuf:"varint,1,opt,name=RoomId,proto3" json:"RoomId,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HeartbeatRequest) Reset()         { *m = HeartbeatRequest{} }
func (m *HeartbeatRequest) String() string { return proto.CompactTextString(m) }
func (*HeartbeatRequest) ProtoMessage()    {}
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{3}
}

func (m *HeartbeatRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HeartbeatRequest.Unmarshal(m, b)
}
func (m *HeartbeatRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HeartbeatRequest.Marshal(b, m, deterministic)
}
func (m *HeartbeatRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeartbeatRequest.Merge(m, src)
}
func (m *HeartbeatRequest) XXX_Size() int {
	return xxx_messageInfo_HeartbeatRequest.Size(m)
}
func (m *HeartbeatRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HeartbeatRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HeartbeatRequest proto.InternalMessageInfo

func (m *HeartbeatRequest) GetRoomId() int32 {
	if m != nil {
		return m.RoomId
	}
	return 0
}

func (m *HeartbeatRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type OfflineBroadCast struct {
	RoomId               int32    `protobuf:"varint,1,opt,name=RoomId,proto3" json:"RoomId,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OfflineBroadCast) Reset()         { *m = OfflineBroadCast{} }
func (m *OfflineBroadCast) String() string { return proto.CompactTextString(m) }
func (*OfflineBroadCast) ProtoMessage()    {}
func (*OfflineBroadCast) Descriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{4}
}

func (m *OfflineBroadCast) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OfflineBroadCast.Unmarshal(m, b)
}
func (m *OfflineBroadCast) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OfflineBroadCast.Marshal(b, m, deterministic)
}
func (m *OfflineBroadCast) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OfflineBroadCast.Merge(m, src)
}
func (m *OfflineBroadCast) XXX_Size() int {
	return xxx_messageInfo_OfflineBroadCast.Size(m)
}
func (m *OfflineBroadCast) XXX_DiscardUnknown() {
	xxx_messageInfo_OfflineBroadCast.DiscardUnknown(m)
}

var xxx_messageInfo_OfflineBroadCast proto.InternalMessageInfo

func (m *OfflineBroadCast) GetRoomId() int32 {
	if m != nil {
		return m.RoomId
	}
	return 0
}

func (m *OfflineBroadCast) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*Player)(nil), "msg.Player")
	proto.RegisterType((*LoginRequest)(nil), "msg.LoginRequest")
	proto.RegisterType((*MatchCompleteBroadCast)(nil), "msg.MatchCompleteBroadCast")
	proto.RegisterType((*HeartbeatRequest)(nil), "msg.HeartbeatRequest")
	proto.RegisterType((*OfflineBroadCast)(nil), "msg.OfflineBroadCast")
}

func init() { proto.RegisterFile("login.proto", fileDescriptor_67c21677aa7f4e4f) }

var fileDescriptor_67c21677aa7f4e4f = []byte{
	// 287 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x91, 0x4f, 0x4b, 0xc3, 0x40,
	0x10, 0xc5, 0xd9, 0x36, 0x89, 0x74, 0x52, 0x44, 0xf7, 0x50, 0xf6, 0x20, 0x12, 0x02, 0x42, 0x0e,
	0x12, 0x30, 0xde, 0x3d, 0x18, 0x0f, 0x0a, 0xfe, 0x63, 0x7b, 0x69, 0x8f, 0xdb, 0x76, 0x1a, 0x03,
	0x49, 0xb6, 0x6e, 0xa6, 0x07, 0xbf, 0xad, 0x1f, 0x45, 0xb2, 0x69, 0x48, 0x8a, 0x78, 0xf0, 0xb6,
	0x6f, 0x66, 0x1e, 0xfc, 0xde, 0x3e, 0xf0, 0x0b, 0x9d, 0xe5, 0x55, 0xbc, 0x33, 0x9a, 0x34, 0x1f,
	0x97, 0x75, 0x16, 0x56, 0xe0, 0xbd, 0x17, 0xea, 0x0b, 0x0d, 0xe7, 0xe0, 0xbc, 0xaa, 0x12, 0x05,
	0x0b, 0x58, 0x34, 0x91, 0xf6, 0xcd, 0x67, 0xe0, 0x49, 0xad, 0xcb, 0xa7, 0x8d, 0x18, 0x05, 0x2c,
	0x72, 0xe5, 0x41, 0xf1, 0x29, 0xb0, 0x85, 0x18, 0x07, 0x2c, 0x1a, 0x49, 0xb6, 0x68, 0xd4, 0x52,
	0x38, 0xad, 0x5a, 0xf2, 0x0b, 0x98, 0x3c, 0xe4, 0x06, 0xd7, 0x94, 0xeb, 0x4a, 0xb8, 0xd6, 0xd6,
	0x0f, 0xc2, 0x53, 0x98, 0x3e, 0x37, 0x0c, 0x12, 0x3f, 0xf7, 0x58, 0x53, 0xf8, 0xcd, 0x60, 0xf6,
	0xa2, 0x68, 0xfd, 0x91, 0xea, 0x72, 0x57, 0x20, 0xe1, 0xbd, 0xd1, 0x6a, 0x93, 0xaa, 0x9a, 0xf8,
	0x25, 0x80, 0xdd, 0xcc, 0x49, 0x51, 0x8b, 0xe5, 0xca, 0xc1, 0xa4, 0x01, 0x9e, 0x23, 0x76, 0x68,
	0xf6, 0x3d, 0x00, 0x1e, 0x1f, 0x01, 0x5f, 0xc3, 0x79, 0xba, 0x37, 0x06, 0x2b, 0x6a, 0xd3, 0xda,
	0xa4, 0x8e, 0x4d, 0xfa, 0x7b, 0xc1, 0xaf, 0xe0, 0xa4, 0x55, 0x37, 0x36, 0x80, 0x9f, 0xf8, 0x71,
	0x59, 0x67, 0x71, 0x3b, 0x93, 0xdd, 0xae, 0x3f, 0x4b, 0x84, 0xf7, 0xe7, 0x59, 0x12, 0xde, 0xc1,
	0xd9, 0x23, 0x2a, 0x43, 0x2b, 0x54, 0x74, 0x88, 0x3d, 0xe0, 0x64, 0x47, 0x9c, 0x5d, 0x09, 0xa3,
	0xbe, 0x84, 0xc6, 0xff, 0xb6, 0xdd, 0x16, 0x79, 0x35, 0xf8, 0x9b, 0x7f, 0xf8, 0x57, 0x9e, 0xad,
	0xfb, 0xf6, 0x27, 0x00, 0x00, 0xff, 0xff, 0xb5, 0x25, 0x60, 0xa3, 0xfd, 0x01, 0x00, 0x00,
}
