// Code generated by protoc-gen-go. DO NOT EDIT.
// source: move.proto

package msg

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PlayerMoveBroadCast struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	RoomId               int32    `protobuf:"varint,2,opt,name=RoomId,proto3" json:"RoomId,omitempty"`
	X                    float32  `protobuf:"fixed32,3,opt,name=X,proto3" json:"X,omitempty"`
	Y                    float32  `protobuf:"fixed32,4,opt,name=Y,proto3" json:"Y,omitempty"`
	Direction            int32    `protobuf:"varint,5,opt,name=Direction,proto3" json:"Direction,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlayerMoveBroadCast) Reset()         { *m = PlayerMoveBroadCast{} }
func (m *PlayerMoveBroadCast) String() string { return proto.CompactTextString(m) }
func (*PlayerMoveBroadCast) ProtoMessage()    {}
func (*PlayerMoveBroadCast) Descriptor() ([]byte, []int) {
	return fileDescriptor_a434d77a673f848c, []int{0}
}

func (m *PlayerMoveBroadCast) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerMoveBroadCast.Unmarshal(m, b)
}
func (m *PlayerMoveBroadCast) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerMoveBroadCast.Marshal(b, m, deterministic)
}
func (m *PlayerMoveBroadCast) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerMoveBroadCast.Merge(m, src)
}
func (m *PlayerMoveBroadCast) XXX_Size() int {
	return xxx_messageInfo_PlayerMoveBroadCast.Size(m)
}
func (m *PlayerMoveBroadCast) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerMoveBroadCast.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerMoveBroadCast proto.InternalMessageInfo

func (m *PlayerMoveBroadCast) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PlayerMoveBroadCast) GetRoomId() int32 {
	if m != nil {
		return m.RoomId
	}
	return 0
}

func (m *PlayerMoveBroadCast) GetX() float32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *PlayerMoveBroadCast) GetY() float32 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *PlayerMoveBroadCast) GetDirection() int32 {
	if m != nil {
		return m.Direction
	}
	return 0
}

func init() {
	proto.RegisterType((*PlayerMoveBroadCast)(nil), "msg.PlayerMoveBroadCast")
}

func init() { proto.RegisterFile("move.proto", fileDescriptor_a434d77a673f848c) }

var fileDescriptor_a434d77a673f848c = []byte{
	// 145 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xca, 0xcd, 0x2f, 0x4b,
	0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xce, 0x2d, 0x4e, 0x57, 0xaa, 0xe6, 0x12, 0x0e,
	0xc8, 0x49, 0xac, 0x4c, 0x2d, 0xf2, 0xcd, 0x2f, 0x4b, 0x75, 0x2a, 0xca, 0x4f, 0x4c, 0x71, 0x4e,
	0x2c, 0x2e, 0x11, 0x12, 0xe2, 0x62, 0xf1, 0x4b, 0xcc, 0x4d, 0x95, 0x60, 0x54, 0x60, 0xd4, 0xe0,
	0x0c, 0x02, 0xb3, 0x85, 0xc4, 0xb8, 0xd8, 0x82, 0xf2, 0xf3, 0x73, 0x3d, 0x53, 0x24, 0x98, 0x14,
	0x18, 0x35, 0x58, 0x83, 0xa0, 0x3c, 0x21, 0x1e, 0x2e, 0xc6, 0x08, 0x09, 0x66, 0x05, 0x46, 0x0d,
	0xa6, 0x20, 0xc6, 0x08, 0x10, 0x2f, 0x52, 0x82, 0x05, 0xc2, 0x8b, 0x14, 0x92, 0xe1, 0xe2, 0x74,
	0xc9, 0x2c, 0x4a, 0x4d, 0x2e, 0xc9, 0xcc, 0xcf, 0x93, 0x60, 0x05, 0x6b, 0x43, 0x08, 0x24, 0xb1,
	0x81, 0x1d, 0x62, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0xe7, 0x58, 0x79, 0x97, 0x96, 0x00, 0x00,
	0x00,
}
